name: sehr_remake
description: A new Flutter project.

publish_to: "none"

version: 1.4.2+33

environment:
  sdk: ">=3.5.1 <4.0.0"


dependencies:
  cached_network_image: ^3.3.0
  change_app_package_name: ^1.1.0
  cupertino_icons: ^1.0.2
  firebase_auth: 5.3.2
  firebase_core: 3.7.0
  fl_chart: null
  flutter:
    sdk: flutter
  flutter_carousel_widget: ^2.1.0
  flutter_pin_code_fields: ^2.2.0
  geocoding: ^2.1.1
  geolocator: ^10.0.1
  get: ^4.6.5
  google_fonts: ^5.1.0
  google_maps_flutter: ^2.5.0
  http: null
  image_picker: ^1.0.4
  intl:
  permission_handler: ^10.4.4
  pie_chart: ^5.3.2
  provider: null
  rename_app: ^1.3.1
  shared_preferences: ^2.2.1
  syncfusion_flutter_charts:
  url_launcher: ^6.1.14
  video_player: ^2.7.1
  webview_flutter: ^2.0.10
  youtube_player_flutter: ^8.1.2
  lottie: ^2.2.0
  flutter_spinkit: ^5.2.1
  sms_autofill: ^2.4.0
  device_preview:
  pretty_animated_buttons: ^0.0.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/images/
    - assets/animations/

  fonts:
    - family: BentonSans
      fonts:
        - asset: assets/fonts/BentonSans Regular.otf
          # weight: 400
        - asset: assets/fonts/BentonSans Medium.otf
          weight: 500
        - asset: assets/fonts/BentonSans Medium.otf
          weight: 700
    - family: UrduFont
      fonts:
        - asset: assets/fonts/Jameel Noori Nastaleeq.ttf
    - family: Nafees
      fonts:
        - asset: assets/fonts/Nafees Regular.ttf

