// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDIp-QXufq1W0u1ennq7ojUddAb5GV5Oc',
    appId: '1:1049835585992:web:a0500754694fc5dc0240fd',
    messagingSenderId: '1049835585992',
    projectId: 'sehr-f33bb',
    authDomain: 'sehr-f33bb.firebaseapp.com',
    storageBucket: 'sehr-f33bb.appspot.com',
    measurementId: 'G-D9VEFSKK2V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBg4ZzvEribkceqi-U7UR-C8KG-zAoOWKg',
    appId: '1:1049835585992:android:0850d112569247150240fd',
    messagingSenderId: '1049835585992',
    projectId: 'sehr-f33bb',
    storageBucket: 'sehr-f33bb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqTukLt5u_NP5sdwFSz5dXznQJ4hHr8vo',
    appId: '1:1049835585992:ios:9e079d77776f3b0c0240fd',
    messagingSenderId: '1049835585992',
    projectId: 'sehr-f33bb',
    storageBucket: 'sehr-f33bb.appspot.com',
    iosBundleId: 'com.example.sehrRemake',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqTukLt5u_NP5sdwFSz5dXznQJ4hHr8vo',
    appId: '1:1049835585992:ios:335f585d6491d1d30240fd',
    messagingSenderId: '1049835585992',
    projectId: 'sehr-f33bb',
    storageBucket: 'sehr-f33bb.appspot.com',
    iosBundleId: 'com.example.sehrRemake.RunnerTests',
  );
}
